### ISSUE TITLE
panic: didn't find any token of type TokenIdent

### ISSUE THREAD

**Issue by mattsawyer77** [apparentlymart/terraform-clean-syntax#2] opened 2019-12-04 01:26 UTC
First of all, thanks @apparentlymart for writing this tool!! I've run it on a large number of directories in my repository and it seems to have cleaned a lot of syntax up. But I am also seeing several of these kinds of errors:

```
panic: didn't find any token of type TokenIdent
```

Are these meaningful errors, or noise?

**Comment by mattsawyer77** [comment] 2019-12-04 01:28
btw, I built this with go 1.13.4 on macOS. the full stack trace looks like this:

```
goroutine 1 [running]:
github.com/hashicorp/hcl/v2/hclwrite.inputTokens.PartitionType(0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0x49, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:88 +0x580
github.com/hashicorp/hcl/v2/hclwrite.inputTokens.PartitionTypeSingle(0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0xc000000049, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:92 +0xe3
github.com/hashicorp/hcl/v2/hclwrite.parseTraversalStep(0x130e460, 0xc000298050, 0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0xc00036be20, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:395 +0x364
github.com/hashicorp/hcl/v2/hclwrite.parseTraversal(0xc000263280, 0x3, 0x4, 0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0xc00036be20, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:377 +0x3da
github.com/hashicorp/hcl/v2/hclwrite.parseExpression(0x130faa0, 0xc0000b6700, 0xc00036be20, 0x2, 0x2, 0xc0003c5fd8, 0x2, 0x2, 0x18b)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:356 +0x175
github.com/hashicorp/hcl/v2/hclwrite.parseAttribute(0xc00028bea0, 0xc00036ba60, 0x0, 0x0, 0xc0003c5f88, 0x0, 0x0, 0xc00036b9a0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:260 +0xaf4
github.com/hashicorp/hcl/v2/hclwrite.parseBodyItem(0x130cc20, 0xc00028bea0, 0xc00036b9a0, 0x17, 0x17, 0xc0003c5f78, 0x17, 0x17, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:217 +0x632
github.com/hashicorp/hcl/v2/hclwrite.parseBody(0xc0000b5a20, 0xc00036af20, 0x33, 0x33, 0xc0003c5e98, 0x33, 0x33, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:193 +0x68d
github.com/hashicorp/hcl/v2/hclwrite.parseBlock(0xc000286b40, 0xc00036af20, 0x0, 0x0, 0xc0003c5e98, 0x0, 0x0, 0xc00036aa40, 0x5, 0x5, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:329 +0xf72
github.com/hashicorp/hcl/v2/hclwrite.parseBodyItem(0x130cc60, 0xc000286b40, 0xc00036a9e0, 0x70, 0x70, 0xc0003c5e28, 0x70, 0x70, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:219 +0x4f7
github.com/hashicorp/hcl/v2/hclwrite.parseBody(0xc0000b5b80, 0xc00033c000, 0x836, 0xa00, 0xc0003c2000, 0x836, 0x836, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:193 +0x68d
github.com/hashicorp/hcl/v2/hclwrite.parse(0xc000102000, 0x38eb, 0x3aeb, 0xc0000e41e0, 0x1c, 0x1, 0x1, 0x0, 0xc0000c3c48, 0xc000000000, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:53 +0x2e4
github.com/hashicorp/hcl/v2/hclwrite.ParseConfig(...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/public.go:27
main.processFile(0xc0000e41e0, 0x1c, 0x1a4)
        /Users/sawyer/terraform-clean-syntax/main.go:75 +0xc8
main.processItem(0xc0000e41e0, 0x1c)
        /Users/sawyer/terraform-clean-syntax/main.go:52 +0x25d
main.processDir(0x7ffeefbff63f, 0x16)
        /Users/sawyer/terraform-clean-syntax/main.go:64 +0x119
main.processItem(0x7ffeefbff63f, 0x16)
        /Users/sawyer/terraform-clean-syntax/main.go:44 +0x17b
main.main()
        /Users/sawyer/terraform-clean-syntax/main.go:30 +0xca
```

**Comment by apparentlymart** [comment] 2019-12-04 16:07
Hi @mattsawyer77! Thanks for reporting this.

Unfortunately this seems to be a bug in the underlying HCL library, rather than in this codebase. Terraform doesn't normally exercise the "`hclwrite`" part of HCL, so this wouldn't be something you'd see in everyday use, but it'd be worth fixing it because it's likely that new Terraform features would make use of this functionality to do modify configuration files in future.

I've opened hashicorp/hcl#327 to capture this issue. I'm not sure what exactly is going on with this yet, since the panic seems to suggest something unusual happened during the main HCL parsing. If you're able to narrow down some specific files that are causing this panic which you'd be able to share in that other issue in the HCL repository, that'd be very useful in creating a reproduction case so I can see if I can figure out what situation causes it.

I'm going to close this one just because I don't think there's anything I could do in this repository in particular to work around that crash. The HCL repository is where this fix would need to be made. Thanks again!

**Closed as completed by apparentlymart** 2019-12-04 16:07 UTC

**Comment by pdecat** [comment] 2019-12-05 10:54
Just faced this with the following configuration:

```tf
resource "google_pubsub_subscription_iam_policy" "pubsub_subscriptions_subscribers" {
  count = length(var.subscriptions)

  subscription = google_pubsub_subscription.pubsub_subscriptions[count.index].name
  policy_data  = data.google_iam_policy.pubsub_subscriptions_subscribers[count.index].policy_data
}
```

A debugging session shows it fails on the `subscription` attribute.

The stack trace:

```
# terraform-clean-syntax ~/workspaces/tests/tf/TCS-2/test.tf
panic: didn't find any token of type TokenIdent

goroutine 1 [running]:
github.com/hashicorp/hcl/v2/hclwrite.inputTokens.PartitionType(0xc00014e2e0, 0x0, 0x0, 0xc0000a32c8, 0x0, 0x0, 0x49, 0x0, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:88 +0x580
github.com/hashicorp/hcl/v2/hclwrite.inputTokens.PartitionTypeSingle(0xc00014e2e0, 0x0, 0x0, 0xc0000a32c8, 0x0, 0x0, 0x7ffd00000049, 0x0, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:92 +0xe3
github.com/hashicorp/hcl/v2/hclwrite.parseTraversalStep(0x709ac0, 0xc0000ba7d0, 0xc00014e2e0, 0x0, 0x0, 0xc0000a32c8, 0x0, 0x0, 0xc00014e2e0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:395 +0x364
github.com/hashicorp/hcl/v2/hclwrite.parseTraversal(0xc0000aae60, 0x2, 0x2, 0xc00014e2e0, 0x0, 0x0, 0xc0000a32c8, 0x0, 0x0, 0xc00014e2e0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:377 +0x3da
github.com/hashicorp/hcl/v2/hclwrite.parseExpression(0x70b080, 0xc0000c4bd0, 0xc00014e2e0, 0x2, 0x2, 0xc0000a32c8, 0x2, 0x2, 0x4)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:356 +0x175
github.com/hashicorp/hcl/v2/hclwrite.parseAttribute(0xc0000d42a0, 0xc00014dfe0, 0x0, 0x0, 0xc0000a3288, 0x0, 0x0, 0xc00014dec0, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:260 +0xaf4
github.com/hashicorp/hcl/v2/hclwrite.parseBodyItem(0x7082e0, 0xc0000d42a0, 0xc00014dec0, 0x1d, 0x1d, 0xc0000a3270, 0x1d, 0x1d, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:217 +0x632
github.com/hashicorp/hcl/v2/hclwrite.parseBody(0xc0000c2580, 0xc00014db00, 0x27, 0x27, 0xc0000a3220, 0x27, 0x27, 0x0, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:193 +0x68d
github.com/hashicorp/hcl/v2/hclwrite.parseBlock(0xc0000be6c0, 0xc00014db00, 0x0, 0x0, 0xc0000a3220, 0x0, 0x0, 0xc00014d800, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:329 +0xf72
github.com/hashicorp/hcl/v2/hclwrite.parseBodyItem(0x708320, 0xc0000be6c0, 0xc00014d800, 0x32, 0x32, 0xc0000a31e0, 0x32, 0x32, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:219 +0x4f7
github.com/hashicorp/hcl/v2/hclwrite.parseBody(0xc0000c2630, 0xc00014d800, 0x33, 0x40, 0xc0000a31e0, 0x33, 0x33, 0x0, 0x0, 0x0, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:193 +0x68d
github.com/hashicorp/hcl/v2/hclwrite.parse(0xc000148000, 0x133, 0x333, 0x7ffdde280e32, 0x2f, 0x1, 0x1, 0x0, 0xffffffffffffff9c, 0xc0000b0210, ...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:53 +0x2e4
github.com/hashicorp/hcl/v2/hclwrite.ParseConfig(...)
        /home/patrick/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/public.go:27
main.processFile(0x7ffdde280e32, 0x2f, 0x1a4)
        /home/patrick/go/pkg/mod/github.com/apparentlymart/terraform-clean-syntax@v0.0.0-20191204155136-6e9583834134/main.go:78 +0xc8
main.processItem(0x7ffdde280e32, 0x2f)
        /home/patrick/go/pkg/mod/github.com/apparentlymart/terraform-clean-syntax@v0.0.0-20191204155136-6e9583834134/main.go:55 +0x2e7
main.main()
        /home/patrick/go/pkg/mod/github.com/apparentlymart/terraform-clean-syntax@v0.0.0-20191204155136-6e9583834134/main.go:30 +0xec
```

**Comment by pdecat** [comment] 2019-12-05 11:32
Maybe `terraform-clean-syntax` could skip files it cannot format for the time being?

Submitted #4 as a quick POC.
